version: 3

vars:
  DEV_ENV_PATH: "configs/envs/.env.dev"
  DEV_DC_PATH: "compose-dev.yaml"

  PROD_ENV_PATH: "configs/envs/.env.prod"
  PROD_DC_PATH: "compose.yaml"

  TEST_ENV_FILE: "configs/envs/.env.test"
  TEST_DOCKER_COMPOSE_PATH: "compose-test.yaml"

tasks:
  dc-prod:
    desc: Run prod compose
    cmds:
      - "docker compose --env-file {{.PROD_ENV_PATH}} -f {{.PROD_DC_PATH}} up --watch"

  dc-prod-build:
    desc: Build prod compose
    cmds:
      - "docker compose --env-file {{.PROD_ENV_PATH}} -f {{.PROD_DC_PATH}} up --build --watch"

  dc-prod-down:
    desc: Shutdown prod compose
    cmds:
      - "docker compose --env-file {{.PROD_ENV_PATH}} -f {{.PROD_DC_PATH}} down"

  dc-prod-obs:
    desc: Run prod compose with observe
    cmds:
      - "docker compose --env-file {{.PROD_ENV_PATH}} -f {{.PROD_DC_PATH}} --profile observe up --watch"

  dc-prod-obs-down:
    desc: Shutdown prod compose with observe containers
    cmds:
      - "docker compose --env-file {{.PROD_ENV_PATH}} -f {{.PROD_DC_PATH}} --profile observe down"

  dc-dev:
    desc: Run dev compose
    cmds:
      - "docker compose --env-file {{.DEV_ENV_PATH}} -f {{.DEV_DC_PATH}} up --watch"

  dc-dev-build:
    desc: Run dev compose
    cmds:
      - "docker compose --env-file {{.DEV_ENV_PATH}} -f {{.DEV_DC_PATH}} up --build --watch"

  dc-dev-down:
    desc: Shutdown dev compose
    cmds:
      - "docker compose --env-file {{.DEV_ENV_PATH}} -f {{.DEV_DC_PATH}} down"

  dc-dev-obs:
    desc: Run dev compose with observe
    cmds:
      - "docker compose --env-file {{.DEV_ENV_PATH}} -f {{.DEV_DC_PATH}} --profile observe up --watch"

  dc-dev-obs-down:
    desc: Shutdown dev compose with observe containers
    cmds:
      - "docker compose --env-file {{.DEV_ENV_PATH}} -f {{.DEV_DC_PATH}} --profile observe down"

  k-up:
    desc: Run k8s manifests
    cmds:
      - "kubectl apply -f k8s/cfg/cfg.yaml"
      - "kubectl apply -f k8s/cfg/secret.yaml"
      - "kubectl apply -f k8s/backend/deploy.yaml"
      - "kubectl apply -f k8s/frontend/deploy.yaml"

  k-down:
    desc: Remove k8s manifests
    cmds:
      - "kubectl delete -f k8s/cfg/cfg.yaml"
      - "kubectl delete -f k8s/cfg/secret.yaml"
      - "kubectl delete -f k8s/backend/deploy.yaml"
      - "kubectl delete -f k8s/frontend/deploy.yaml"
