apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-template-frontend
  labels:
    app: app-template-frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-template-frontend
  template:
    metadata:
      labels:
        app: app-template-frontend
    spec:
      containers:
        - name: app
          image: jmurv/app-template-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4000

---
apiVersion: v1
kind: Service

metadata:
  name: app-template-frontend
  labels:
    app: app-template-frontend

spec:
  selector:
    app: app-template-frontend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30400

  type: NodePort